-- Aggregate analysis supplement: age groups and coded gender.
SELECT CASE WHEN AGE/365 < 40 THEN '<40'
            WHEN AGE/365 < 50 THEN '40-49'
            WHEN AGE/365 < 60 THEN '50-59' ELSE '60+' END AS AGE_GROUP,
       GENDER, COUNT(*) AS RECORDS, SUM(CARDIO) AS CASES,
       ROUND(100.0*AVG(CARDIO),2) AS CASE_PERCENT
FROM CARDIO_TRAIN GROUP BY AGE_GROUP,GENDER ORDER BY AGE_GROUP,GENDER;
